INSERT INTO [dbo].[Branch] ([Branch_ID],[Branch_Name],[Branch_Gov]) VALUES
(1,'Smart Village','Cairo'),
(2,'New Capital','Cairo'),
(3,'Cairo University','Cairo'),
(4,'Alexandria','Alexandria'),
(5,'Assiut','Assiut'),
(6,'Aswan','Aswan'),
(7,'Beni Suef','Beni Suef'),
(8,'Fayoum','Fayoum'),
(9,'Mansoura','Mansoura'),
(10,'Menofia','Menofia'),
(11,'Minya','Minya'),
(12,'Qena','Qena'),
(13,'Sohag','Sohag'),
(14,'Ismailia','Ismailia');