
INSERT INTO [dbo].[Track] ([Track_ID],[Track_Name]) VALUES
(1,'Power BI Developer'),
(2,'Full Stack Web Development Using .Net'),
(3,'Full Stack Web Development using PHP'),
(4,'Full Stack Web Development using Python'),
(5,'Full Stack Web Development Using MERN'),
(6,'Data Engineering'),
(7,'Data Managment'),
(8,'UI/UX Design'),
(9,'2D Graphics Design'),
(10,'Furniture Design and Visualization'),
(11,'Software Testing'),
(12,'Database Administrator'),
(13,'Microsoft Azure Administration'),
(14,'Business Analysis'),
(15,'Software Development Fundamentals'),
(16,'iOS Mobile Application Developmen'),
(17,'Mobile Applications Development For Android'),
(18,'Blockchain Development'),
(19,'Web Development Using CMS'),
(20,'System Administrator');